# Generated by Django 4.0.2 on 2022-08-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userprofile_questionsattempted'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionProfile',
            fields=[
                ('question', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('answer', models.CharField(max_length=1)),
                ('questionNumber', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
