# Generated by Django 4.0.2 on 2022-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questionprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='NextQuestionToAnswer',
            field=models.IntegerField(default=1),
        ),
    ]
