# Generated by Django 4.0.2 on 2022-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questionsansweredwrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsansweredwrong',
            name='creationTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
