# Generated by Django 4.0.2 on 2022-09-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_questionsansweredwrong_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='countDownToDisplayWrongAnswer',
            field=models.IntegerField(default=4),
        ),
    ]
